version: "3"

services:

  gor_rest_server:
    container_name: gor_rest_server
    image: supertypo/gor-rest-server:latest
    restart: unless-stopped
    environment:
      KASPAD_HOST_1: 203.161.35.197:18110
      VERSION: 2.1.0
      SQL_URI: postgresql+asyncpg://brics:1@172.17.0.1:5432/brics
    ports:
      - "8000:8000/tcp"

  kaspa_socket_server:
    container_name: kaspa_socket_server
    image: lamer1/kaspa-socket-server:latest
    restart: unless-stopped
    environment:
      KASPAD_HOST_1: 203.161.35.197:18110
      SQL_URI: postgresql+asyncpg://brics:1@172.17.0.1:5432/brics
    ports:
      - "8001:8000/tcp"

  kaspa_db_filler:
    container_name: kaspa_db_filler
    image: supertypo/kaspa-db-filler:latest
    restart: unless-stopped
    environment:
      KASPAD_HOST_1: 203.161.35.197:18110
      SQL_URI: postgresql://brics:1@172.17.0.1:5432/brics

